'use strict';
const $=id=>document.getElementById(id),Store=window.VaultStore;
const FIXED_TAGS=['读书笔记','灵感碎片','学习笔记','生活感悟'];
const TAG_COLORS={'读书笔记':'#10b981','灵感碎片':'#8b5cf6','学习笔记':'#f59e0b','生活感悟':'#f43f5e'};
function orderedTags(counts={}){return [...FIXED_TAGS.map(tag=>[tag,counts[tag]||0]),...Object.entries(counts).filter(([tag])=>!FIXED_TAGS.includes(tag)).sort((a,b)=>b[1]-a[1])];}
const state={online:false,view:'all',tag:'',categoryId:'',collapsedCategories:new Set(),q:'',filterTags:[],filterFrom:'',filterTo:'',filterMedia:'',filterUntagged:false,sort:'updated-desc',page:1,total:0,limit:24,layout:localStorage.getItem('kb-layout')||'card',items:[],stats:null,editing:null,draftId:null,detail:null,selectedMedia:null,saving:false,editRevision:0,lastSavedRevision:0,ready:false};
let syncTask=null,loadToken=0,draftTimer,autoTimer,toastTimer,pendingImport=null,lastRange=null;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join(''),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const formatDate=s=>{try{return new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(s));}catch{return '';}};
function categoryNodes(){return state.stats?.categories||[];}
function categoryPath(id){const byId=new Map(categoryNodes().map(node=>[node.id,node]));const names=[];let node=byId.get(id);while(node){names.unshift(node.name);node=byId.get(node.parentId);}return names;}
function categoryPathText(id){return categoryPath(id).join(' / ');}
function categoryDescendantIds(id){const nodes=categoryNodes(),ids=[id];for(let i=0;i<ids.length;i++)for(const node of nodes)if(node.parentId===ids[i])ids.push(node.id);return ids;}
function renderCategoryTree(s){
 const nodes=s.categories||[],counts=s.categoryCounts||{};
 function branch(parentId){return nodes.filter(node=>node.parentId===parentId).map(node=>{
   const children=nodes.some(child=>child.parentId===node.id),expanded=!state.collapsedCategories.has(node.id);
   return `<div class="category-row depth-${node.depth}"><button class="category-toggle" data-expand-category="${esc(node.id)}" aria-label="${children?(expanded?'收起':'展开'):'无下级'} ${esc(node.name)}" ${children?'':'disabled'}>${children?(expanded?'▾':'▸'):'·'}</button><button class="nav category-item ${state.categoryId===node.id?'active':''}" data-category="${esc(node.id)}"><span class="tag-name">${esc(node.name)}</span><span>${counts[node.id]||0}</span></button>${node.depth<3?`<button class="category-add" data-add-child="${esc(node.id)}" aria-label="在${esc(node.name)}下新增子类">＋</button>`:''}</div>${children&&expanded?branch(node.id):''}`;
 }).join('');}
 const names=new Set(nodes.map(node=>node.name));
 const loose=orderedTags(s.tags||{}).filter(([name,count])=>count&&!names.has(name));
 return branch(null)+(loose.length?'<div class="nav-label">其他标签</div>'+loose.map(([tag,count])=>`<button class="nav ${state.tag===tag?'active':''}" data-tag="${esc(tag)}"><span class="tag-name">${esc(tag)}</span><span>${count}</span></button>`).join(''):'');
}
function categoryOptions(){return '<option value="">不分类</option>'+categoryNodes().map(node=>`<option value="${esc(node.id)}">${esc(categoryPathText(node.id))}</option>`).join('');}
function hideCategoryContextMenu(){const menu=$('categoryContextMenu');menu.hidden=true;delete menu.dataset.parentId;}
function showCategoryContextMenu(event){
 const row=event.target.closest('.category-row');if(!row||!$('tags').contains(row))return;
 const id=row.querySelector('[data-category]')?.dataset.category,node=categoryNodes().find(item=>item.id===id);if(!node)return;
 event.preventDefault();const menu=$('categoryContextMenu'),create=$('categoryContextCreate');
 menu.dataset.parentId=node.id;$('categoryContextTitle').textContent=categoryPathText(node.id);
 create.disabled=node.depth>=3;create.textContent=create.disabled?'已到第三级，不能再建下级':`新建${node.depth+1}级目录`;
 menu.hidden=false;const bounds=menu.getBoundingClientRect();
 menu.style.left=Math.max(8,Math.min(event.clientX,innerWidth-bounds.width-8))+'px';
 menu.style.top=Math.max(8,Math.min(event.clientY,innerHeight-bounds.height-8))+'px';
 if(!create.disabled)create.focus();
}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,4500);}
const sidePane=()=>matchMedia('(min-width: 1200px)').matches;
function showPane(dialog){const overlay=dialog.id==='editorDialog'&&dialog.classList.contains('editor-overlay');if(!dialog.open){if(sidePane()&&!overlay)dialog.show();else dialog.showModal();}document.body.classList.toggle('pane-open',sidePane()&&!overlay);}
function hidePane(dialog){if(dialog.open)dialog.close();if(dialog.id==='editorDialog')dialog.classList.remove('editor-overlay');document.body.classList.toggle('pane-open',sidePane()&&($('editorDialog').open||$('detailDialog').open));if(dialog.id==='editorDialog')document.body.classList.remove('focus-mode');}
function selectedTags(){return $('editTags').value.split(/[,，]/).map(t=>t.trim()).filter(Boolean);}
function updateQuickTags(){const selected=new Set(selectedTags());$('quickTags').querySelectorAll('[data-quick-tag]').forEach(button=>button.setAttribute('aria-pressed',String(selected.has(button.dataset.quickTag))));}
function renderSearchFilters(){const counts=state.stats?.tags||{},names=[...new Set([...FIXED_TAGS,...state.filterTags,...orderedTags(counts).map(([tag])=>tag)])].slice(0,Math.max(20,FIXED_TAGS.length+state.filterTags.length));$('filterTags').innerHTML=names.map(tag=>`<button type="button" data-filter-tag="${esc(tag)}" aria-pressed="${state.filterTags.includes(tag)}">${esc(tag)}</button>`).join('');const active=state.filterTags.length+Number(!!state.filterFrom)+Number(!!state.filterTo)+Number(!!state.filterMedia)+Number(state.filterUntagged);$('filterCount').textContent=active?'· '+active+' 项已选':'';}
function highlight(value,term){const source=String(value||''),needle=String(term||'');if(!needle)return esc(source);const lower=source.toLocaleLowerCase(),search=needle.toLocaleLowerCase();let result='',start=0,at;while((at=lower.indexOf(search,start))!==-1){result+=esc(source.slice(start,at))+'<mark>'+esc(source.slice(at,at+needle.length))+'</mark>';start=at+needle.length;}return result+esc(source.slice(start));}
function plainExcerpt(html){return new DOMParser().parseFromString(String(html||''),'text/html').body.textContent.replace(/\s+/g,' ').trim();}
function listParams(){const params=new URLSearchParams({view:state.view,q:state.q,tag:state.tag,category:state.categoryId,sort:state.sort,page:state.page,limit:state.limit,from:state.filterFrom,to:state.filterTo,media:state.filterMedia,untagged:state.filterUntagged?'1':''});for(const tag of state.filterTags)params.append('tags',tag);return params;}
function matchesLocal(r){if((state.view==='trash'?!!r.deletedAt:!r.deletedAt)===false)return false;if(state.view==='favorites'&&!r.favorite)return false;if(state.tag&&!r.tags.includes(state.tag))return false;if(state.categoryId&&!categoryDescendantIds(state.categoryId).includes(r.categoryId))return false;if(state.filterTags.some(tag=>!r.tags.includes(tag)))return false;if(state.filterUntagged&&r.tags.length)return false;if(state.filterFrom&&r.updatedAt.slice(0,10)<state.filterFrom)return false;if(state.filterTo&&r.updatedAt.slice(0,10)>state.filterTo)return false;if(state.filterMedia==='image'&&!/<img\b/i.test(r.content||''))return false;if(state.filterMedia==='video'&&!/<video\b/i.test(r.content||''))return false;if(state.filterMedia==='none'&&/<(?:img|video)\b/i.test(r.content||''))return false;return !state.q||(r.title+' '+r.summary+' '+(r.content||'')).toLocaleLowerCase().includes(state.q.toLocaleLowerCase());}
function resetFilters(){state.q='';state.tag='';state.categoryId='';state.filterTags=[];state.filterFrom='';state.filterTo='';state.filterMedia='';state.filterUntagged=false;$('search').value='';$('filterFrom').value='';$('filterTo').value='';$('filterMedia').value='';$('filterUntagged').checked=false;renderSearchFilters();}
function mediaUrl(value){if(!value)return '';try{const url=new URL(value,location.origin);if(url.protocol==='http:'||url.protocol==='https:'||/^data:(image\/(png|jpeg|gif|webp|svg\+xml)|video\/(mp4|webm))(;base64)?,/i.test(value))return value;}catch{}return '';}
function sanitize(html){const source=new DOMParser().parseFromString(String(html||''),'text/html'),root=document.createElement('div');const tags=new Set(['P','DIV','SPAN','BR','B','STRONG','I','EM','U','S','STRIKE','H1','H2','H3','H4','UL','OL','LI','BLOCKQUOTE','PRE','CODE','A','IMG','VIDEO','SOURCE','HR','TABLE','THEAD','TBODY','TR','TH','TD']);const denied=new Set(['SCRIPT','STYLE','IFRAME','OBJECT','EMBED','SVG','MATH','TEMPLATE','FORM','INPUT','BUTTON','LINK','META']);
 function copy(node,parent){if(node.nodeType===3){parent.append(document.createTextNode(node.textContent));return;}if(node.nodeType!==1||denied.has(node.tagName))return;if(!tags.has(node.tagName)){for(const child of node.childNodes)copy(child,parent);return;}const el=document.createElement(node.tagName.toLowerCase());if(['IMG','VIDEO','SOURCE'].includes(node.tagName)){const url=mediaUrl(node.getAttribute('src'));if(!url&&node.tagName!=='VIDEO')return;if(url)el.setAttribute('src',url);if(node.tagName==='IMG'){el.alt=node.getAttribute('alt')||'';el.loading='lazy';}if(node.tagName==='VIDEO'){el.controls=true;el.preload='metadata';}}if(node.tagName==='A'){const href=node.getAttribute('href')||'';if(/^(https?:\/\/|mailto:)/i.test(href)){el.href=href;el.target='_blank';el.rel='noopener noreferrer';}}for(const prop of ['width','height']){const v=node.style[prop]||node.getAttribute(prop);if(v&&/^(auto|\d{1,4}(\.\d+)?(px|%)?)$/.test(v))el.style[prop]=/^\d+$/.test(v)?v+'px':v;}for(const prop of ['textAlign','fontWeight','fontStyle','textDecoration','color','backgroundColor']){const v=node.style[prop];if(v&&!/url|expression|var\(/i.test(v))el.style[prop]=v;}for(const child of node.childNodes)copy(child,el);parent.append(el);}for(const child of source.body.childNodes)copy(child,root);return root.innerHTML;}
async function api(url,options={}){let res;try{res=await fetch(url,{...options,signal:options.signal||AbortSignal.timeout(12000),headers:{...(options.body&&!options.binary?{'Content-Type':'application/json'}:{}),...options.headers}});}catch(error){state.online=false;connection();throw error;}if(!res.ok){const data=await res.json().catch(()=>({}));const error=new Error(data.error||`请求失败 (${res.status})`);error.status=res.status;if(res.status===401)showLogin();throw error;}state.online=true;connection();return res.json();}
function connection(){const pending=state.pending||0;$('syncStatus').textContent=!state.online?'离线 · 待连接':pending?`${pending} 项待同步`:'已连接资料库';$('syncStatus').classList.toggle('warning',!state.online||pending>0);}
async function queueState(){const queue=await Store.all('queue');state.pending=queue.length;connection();const blocked=queue.filter(q=>q.error);$('queueBanner').hidden=!queue.length;if(queue.length)$('queueBanner').innerHTML=`<span>${blocked.length?`${blocked.length} 项需要处理，其余修改仍在本地`:`${queue.length} 项修改已保存在此浏览器，等待写入资料库`}</span><button data-action="${blocked.length?'conflicts':'sync'}">${blocked.length?'处理冲突 / 错误':'立即重试'}</button>`;return queue;}
async function sync(){if(syncTask)return syncTask;syncTask=(async()=>{const queue=(await Store.all('queue')).sort((a,b)=>a.createdAt-b.createdAt),blocked=new Set();for(const op of queue){if(blocked.has(op.recordId)||op.error){blocked.add(op.recordId);continue;}try{const saved=await api('/api/operations',{method:'POST',body:JSON.stringify({opId:op.id,action:op.action,id:op.recordId,record:op.record,baseVersion:op.baseVersion})});await Store.remove('queue',op.id);const later=(await Store.all('queue')).some(q=>q.recordId===op.recordId);if(!later)await Store.put('records',saved);}catch(error){if([409,400,404].includes(error.status)){op.error=error.message;op.conflict=error.status===409;await Store.put('queue',op);blocked.add(op.recordId);}else break;}}await queueState();})().finally(()=>{syncTask=null;});return syncTask;}
async function cacheItems(items){const pending=new Set((await Store.all('queue')).map(q=>q.recordId));for(const item of items){if(pending.has(item.id))continue;const old=await Store.get('records',item.id);const content=old&&old.version===item.version?old.content:undefined;await Store.put('records',{...item,...(content!==undefined?{content}:{})});}}
async function refreshStats(){try{state.stats=await api('/api/stats');await Store.put('meta',{id:'stats',value:state.stats});}catch{state.stats=(await Store.get('meta','stats'))?.value||{count:0,favorites:0,week:0,tags:{},trash:0};}const s=state.stats;$('countAll').textContent=s.count;$('countFav').textContent=s.favorites;$('countTrash').textContent=s.trash;$('summary').innerHTML=`共 <b>${s.count}</b> 条记录 · 本周新增 <b>${s.week}</b> 条${!state.online?' · 离线显示已缓存内容':''}`;$('tags').innerHTML=renderCategoryTree(s);renderSearchFilters();}
async function loadList(){const token=++loadToken;$('records').innerHTML='<div class="empty">正在读取记录…</div>';let result;try{result=await api('/api/records?'+listParams());await cacheItems(result.items);if((await Store.all('queue')).length)result=null;}catch{result=null;}if(!result){let items=await Store.all('records');items=items.filter(matchesLocal);items.sort((a,b)=>state.sort==='title-asc'?a.title.localeCompare(b.title,'zh-CN'):state.sort==='updated-asc'?a.updatedAt.localeCompare(b.updatedAt):(state.sort==='created-desc'?b.createdAt.localeCompare(a.createdAt):b.updatedAt.localeCompare(a.updatedAt)));result={total:items.length,items:items.slice((state.page-1)*state.limit,state.page*state.limit)};}if(token!==loadToken)return;state.total=result.total;state.items=result.items;if(!result.items.length&&state.page>1){state.page--;return loadList();}renderList();}
function renderList(){const titles={all:'全部记录',recent:'最近更新',favorites:'收藏夹',trash:'回收站'};$('viewTitle').textContent=state.categoryId?categoryPathText(state.categoryId):state.tag||titles[state.view];$('filterLabel').textContent=`${state.q?`搜索“${state.q}” · `:''}${state.total} 条${!state.online?'已缓存记录（未缓存内容需连接后查看）':''}`;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',!state.tag&&!state.categoryId&&b.dataset.view===state.view));document.querySelectorAll('[data-layout]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.layout===state.layout)));$('records').className='records '+state.layout;if(!state.items.length){const filtered=state.q||state.tag||state.categoryId||state.filterTags.length||state.filterFrom||state.filterTo||state.filterMedia||state.filterUntagged,isTrash=state.view==='trash';$('records').innerHTML=`<div class="empty"><div class="symbol">${isTrash?'↶':'▤'}</div><h2>${filtered?'没有找到相关记录':isTrash?'回收站是空的':state.view==='favorites'?'还没有收藏':'记录从一个想法开始'}</h2><p>${filtered?'试试其他关键词，或清除筛选条件。':isTrash?'移除的记录会保留在这里，你可以随时恢复。':state.view==='favorites'?'将常用记录加入收藏，之后更容易找到。':'文字、图片、视频，都可以放在同一条记录里。'}</p>${filtered?'<button data-action="clear-filter">清除筛选</button>':!isTrash?'<button class="primary" data-action="new">＋ 创建第一条记录</button>':''}</div>`;}else $('records').innerHTML=state.items.map(r=>`<article class="card ${state.detail?.id===r.id||state.editing?.id===r.id?'selected':''}">${mediaUrl(r.cover)?`<img class="card-cover" src="${esc(mediaUrl(r.cover))}" alt="" loading="lazy">`:''}<div class="card-main"><button class="card-title" data-open="${esc(r.id)}">${highlight(r.title,state.q)}</button><p class="card-summary">${highlight(state.q&&r.matchExcerpt?plainExcerpt(r.matchExcerpt):r.summary||'暂无摘要',state.q)}</p><div class="chips">${r.categoryId?`<span class="chip">${esc(categoryPathText(r.categoryId))}</span>`:''}${r.tags.slice(0,4).map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="card-footer"><time datetime="${esc(r.updatedAt)}">${formatDate(r.deletedAt||r.updatedAt)}</time>${state.view==='trash'?`<button data-restore="${esc(r.id)}">恢复</button>`:`<button data-favorite="${esc(r.id)}" aria-label="${r.favorite?'取消收藏':'收藏'} ${esc(r.title)}" aria-pressed="${r.favorite}">${r.favorite?'★':'☆'}</button>`}</div></div></article>`).join('');$('pagination').hidden=state.total<=state.limit;$('pageLabel').textContent=`${state.page} / ${Math.max(1,Math.ceil(state.total/state.limit))}`;document.querySelector('[data-action="prev"]').disabled=state.page<=1;document.querySelector('[data-action="next"]').disabled=state.page*state.limit>=state.total;}
async function fullRecord(id){const local=await Store.get('records',id);if((await Store.all('queue')).some(q=>q.recordId===id)&&local?.content!==undefined)return local;try{const r=await api('/api/records/'+encodeURIComponent(id));await Store.put('records',r);return r;}catch(error){if(local?.content!==undefined)return local;throw new Error('这条记录的正文尚未缓存，请连接资料库后再查看。');}}
async function openDetail(id){try{if($('editorDialog').open&&!await closeEditor())return;const r=await fullRecord(id);state.detail=r;$('detailArticle').innerHTML=`<h1>${esc(r.title)}</h1><div class="muted">更新于 ${formatDate(r.updatedAt)}${r.deletedAt?' · 已在回收站':''}</div><div class="chips">${r.categoryId?`<span class="chip">${esc(categoryPathText(r.categoryId))}</span>`:''}${r.tags.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="rich-content">${sanitize(r.content)}</div>`;$('detailFavorite').textContent=r.favorite?'★ 已收藏':'☆ 收藏';for(const action of ['favorite','edit-detail','delete-detail'])document.querySelector(`[data-action="${action}"]`).hidden=!!r.deletedAt;showPane($('detailDialog'));renderList();}catch(e){toast(e.message);}}
function draftContent(){return {id:state.draftId,recordId:state.editing?.id||null,base:state.editing,title:$('editTitle').value,content:sanitize($('content').innerHTML),tags:$('editTags').value,categoryId:$('editCategory').value||null,updatedAt:Date.now()};}
async function writeDraft(){if(!state.draftId)return;const draft=draftContent();if(!draft.title&&!draft.content&&!draft.tags)return;try{await Store.put('drafts',draft);$('draftState').textContent='草稿已保存在此浏览器 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});await draftBanner();}catch{$('draftState').textContent='草稿保存失败，请勿关闭页面';toast('浏览器存储不足，请复制正文或释放空间后再保存。');throw new Error('草稿未保存');}}
function scheduleDraft(){state.editRevision++;$('draftState').textContent='正在保存…';$('wordCount').textContent=$('content').textContent.trim().length+' 字';updateQuickTags();clearTimeout(draftTimer);clearTimeout(autoTimer);draftTimer=setTimeout(()=>writeDraft().catch(()=>{}),450);autoTimer=setTimeout(()=>{if(!$('editorDialog').open)return;if(!$('content').textContent.trim()&&!$('content').querySelector('img,video')){$('draftState').textContent='草稿已留在浏览器，写入正文后自动保存';return;}saveEditor({auto:true});},1800);}
async function draftBanner(){const drafts=await Store.all('drafts');$('draftBanner').hidden=!drafts.length;$('draftBanner').querySelector('span').textContent=`有 ${drafts.length} 份未完成的草稿`;}
async function openEditor(r=null,draft=null){if($('editorDialog').open&&!await closeEditor())return;state.editing=r;state.draftId=draft?.id||(r?'record-'+r.id:'new-'+uid());if(!draft)draft=await Store.get('drafts',state.draftId);if(draft?.base)state.editing=draft.base;const creating=!state.editing;$('editorDialog').classList.toggle('editor-overlay',creating);$('closeEditor').textContent=creating?'关闭':'← 返回';$('editTitle').value=draft?.title??r?.title??'';$('content').innerHTML=sanitize(draft?.content??r?.content??'');$('editTags').value=draft?.tags??r?.tags?.join('，')??(state.view==='all'?state.tag:'');$('editCategory').innerHTML=categoryOptions();$('editCategory').value=draft?.categoryId??r?.categoryId??state.categoryId??'';$('editorHeading').textContent=creating?'新建记录':'编辑记录';$('draftState').textContent=draft?'已恢复草稿，准备自动保存':'修改后自动保存到本机';$('wordCount').textContent=$('content').textContent.trim().length+' 字';state.editRevision=0;state.lastSavedRevision=0;$('quickTags').innerHTML=orderedTags(state.stats?.tags||{}).slice(0,12).map(([t])=>`<button data-quick-tag="${esc(t)}">${esc(t)}</button>`).join('');updateQuickTags();selectMedia(null);if($('detailDialog').open)hidePane($('detailDialog'));if($('panelDialog').open)$('panelDialog').close();showPane($('editorDialog'));$('editTitle').focus();if(draft)scheduleDraft();}
async function closeEditor(){
  if(state.saving||state.uploading){toast('正在保存或上传，请稍候。');return false;}
  clearTimeout(draftTimer);clearTimeout(autoTimer);
  try{
    if(state.editRevision>state.lastSavedRevision){
      const hasContent=$('content').textContent.trim()||$('content').querySelector('img,video');
      if(hasContent){if(!await saveEditor({auto:true}))return false;}
      else await writeDraft();
    }
    hidePane($('editorDialog'));selectMedia(null);state.draftId=null;
    await draftBanner();renderList();return true;
  }catch(error){toast(error.message||'草稿未保存，请重试。');return false;}
}
async function externalize(html){const root=document.createElement('div');root.innerHTML=sanitize(html);for(const el of root.querySelectorAll('img,video,source')){const src=el.getAttribute('src')||'';if(/^data:(image\/(png|jpeg|gif|webp)|video\/(mp4|webm));base64,/i.test(src)&&state.online){try{const blob=await fetch(src).then(r=>r.blob());const result=await api('/api/attachments',{method:'POST',body:blob,binary:true,headers:{'Content-Type':'application/octet-stream'}});el.src=result.url;}catch{}}}return root.innerHTML;}
async function stage(action,r,baseVersion){const op={id:uid(),recordId:r.id,action,record:r,baseVersion,createdAt:Date.now()};await Store.enqueue(op,r);await queueState();await sync();return {pending:await Store.get('queue',op.id),record:await Store.get('records',r.id)};}
async function saveEditor({auto=false,close=false}={}){
  if(state.uploading){if(!auto)toast('附件正在上传，请稍候再保存。');return false;}
  if(state.saving){if(!auto)toast('正在保存，请稍候。');return false;}
  if(state.editing&&state.editRevision<=state.lastSavedRevision){
    if(close){hidePane($('editorDialog'));selectMedia(null);state.draftId=null;renderList();}
    return true;
  }
  state.saving=true;
  const revision=state.editRevision;
  $('saveEditor').disabled=true;
  $('draftState').textContent='正在保存到本机…';
  try{
    clearTimeout(draftTimer);clearTimeout(autoTimer);
    await writeDraft();
    const content=await externalize($('content').innerHTML),root=document.createElement('div');
    root.innerHTML=content;
    const text=root.textContent.trim();
    if(!text&&!root.querySelector('img,video'))throw new Error('请先写点内容或添加图片、视频。');
    const tags=selectedTags();
    if(tags.some(t=>t.length>60)||tags.length>30)throw new Error('最多 30 个标签，每个不超过 60 字。');
    const existing=state.editing,now=new Date().toISOString();
    const record={id:existing?.id||uid(),title:$('editTitle').value.trim()||text.split(/\n/)[0].slice(0,60)||'图片与视频记录',summary:text.replace(/\s+/g,' ').slice(0,180),content,tags:[...new Set(tags)],categoryId:$('editCategory').value||null,cover:root.querySelector('img')?.getAttribute('src')||null,favorite:existing?.favorite||false,createdAt:existing?.createdAt||now,updatedAt:now,version:existing?existing.version+1:1,deletedAt:null};
    const result=await stage(existing?'update':'create',record,existing?.version);
    state.editing=result.record||record;
    state.lastSavedRevision=revision;
    const previousDraftId=state.draftId;
    state.draftId='record-'+record.id;
    await Store.remove('drafts',previousDraftId);
    if(previousDraftId!==state.draftId)await Store.remove('drafts',state.draftId);
    $('draftState').textContent=result.pending?'已存浏览器 · 待同步':'已保存到本机 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
    await draftBanner();await refreshStats();await loadList();
    if(close){hidePane($('editorDialog'));selectMedia(null);state.draftId=null;renderList();}
    if(!auto)toast(result.pending?'已保存到浏览器，等待写入资料库。':'已保存到资料库');
    return true;
  }catch(error){
    $('draftState').textContent='保存失败 · 内容仍在草稿中';
    if(!auto)toast(error.message||'保存失败，编辑内容仍保留。');
    return false;
  }finally{
    state.saving=false;$('saveEditor').disabled=false;$('saveEditor').textContent='完成';
    if(state.editRevision>revision&&$('editorDialog').open){clearTimeout(autoTimer);autoTimer=setTimeout(()=>saveEditor({auto:true}),1200);}
  }
}
async function favorite(id){try{if($('editorDialog').open&&state.editing?.id===id&&!await closeEditor())return;const r=await fullRecord(id),version=r.version;r.favorite=!r.favorite;r.version++;r.updatedAt=new Date().toISOString();const result=await stage('update',r,version);toast(result.pending?'收藏更改已保存本地，待同步':'收藏已更新');if($('detailDialog').open)await openDetail(id);await refreshStats();await loadList();}catch(e){toast(e.message);}}
async function trash(id,restore=false){try{if($('editorDialog').open&&state.editing?.id===id&&!await closeEditor())return;const r=await fullRecord(id),version=r.version;r.deletedAt=restore?null:new Date().toISOString();r.version++;r.updatedAt=new Date().toISOString();const result=await stage(restore?'restore':'delete',r,version);if($('detailDialog').open)hidePane($('detailDialog'));state.detail=null;toast(result.pending?'更改已保存本地，待同步':restore?'记录已恢复':'已移入回收站，可随时恢复');await refreshStats();await loadList();}catch(e){toast(e.message);}}
async function showHistory(){
  if(!state.detail)return;
  try{
    const versions=await api('/api/records/'+encodeURIComponent(state.detail.id)+'/history');
    let html='<p class="muted">当前为版本 '+state.detail.version+'。恢复旧版后仍可从历史记录中找回当前内容。</p>';
    html+=versions.map(item=>'<div class="history-item"><div><b>版本 '+item.version+'</b><div class="muted">'+esc(formatDate(item.savedAt))+'</div></div><button data-history-version="'+item.version+'">查看</button></div>').join('')||'<p>这条记录还没有旧版本。</p>';
    panel('历史版本',html);
  }catch(error){toast(error.message);}
}
async function showHistoryVersion(version){
  try{
    const snapshot=await api('/api/records/'+encodeURIComponent(state.detail.id)+'/history/'+encodeURIComponent(version));
    panel('版本 '+version+' · '+snapshot.title,'<p class="muted">保存于 '+esc(formatDate(snapshot.updatedAt))+'</p><div class="history-preview"><div class="rich-content">'+sanitize(snapshot.content)+'</div></div><button data-action="history">返回版本列表</button><button class="primary" data-restore-version="'+version+'">恢复此版本</button>');
  }catch(error){toast(error.message);}
}
async function restoreVersion(version){
  try{
    const id=state.detail.id;
    const saved=await api('/api/operations',{method:'POST',body:JSON.stringify({opId:uid(),action:'restore-version',id,baseVersion:state.detail.version,targetVersion:Number(version)})});
    await Store.put('records',saved);
    $('panelDialog').close();
    await openDetail(id);
    await refreshStats();
    await loadList();
    toast('已恢复旧版，恢复前的内容也保留在历史记录中。');
  }catch(error){toast(error.message);}
}
function panel(title,html){$('panelTitle').textContent=title;$('panelBody').innerHTML=html;if(!$('panelDialog').open)$('panelDialog').showModal();}
function showAddCategory(parentId=''){
 const options='<option value="">一级类目</option>'+categoryNodes().filter(node=>node.depth<3).map(node=>`<option value="${esc(node.id)}">${esc(categoryPathText(node.id))} 下级</option>`).join('');
 panel('新增知识类目',`<p class="muted">最多三级。例如：后期 → 后期资料 → AI。每一级都可手动新增，固定的四个方向会继续保留。</p><label class="field">上级类目<select id="categoryParent">${options}</select></label><label class="field">类目名称<input id="categoryName" maxlength="60" placeholder="例如：Houdini" autocomplete="off"></label><button class="primary" data-action="save-category">添加类目</button>`);
 $('categoryParent').value=parentId;$('categoryName').focus();$('categoryName').addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();saveCategory();}});
}
async function saveCategory(){try{const name=$('categoryName').value.trim(),parentId=$('categoryParent').value||null;if(!name)throw new Error('请输入类目名称');const result=await api('/api/categories',{method:'POST',body:JSON.stringify({name,parentId})});$('panelDialog').close();state.view='all';state.tag='';state.categoryId=result.id;state.page=1;if(parentId)state.collapsedCategories.delete(parentId);await refreshStats();await loadList();toast('类目已添加，下一条新记录会自动归入这里。');}catch(error){toast(error.message);}}
async function showDrafts(){const drafts=(await Store.all('drafts')).sort((a,b)=>b.updatedAt-a.updatedAt);panel('继续编辑草稿',drafts.map(d=>`<div class="draft-item"><div><b>${esc(d.title||'未命名草稿')}</b><div class="muted">${formatDate(d.updatedAt)}</div></div><button data-draft="${esc(d.id)}">继续编辑</button></div>`).join('')||'<p>没有未完成的草稿。</p>');}
async function conflicts(){const queue=await Store.all('queue'),ids=[...new Set(queue.filter(q=>q.error).map(q=>q.recordId))];let html='<p class="muted">你的修改仍保存在此浏览器。另存为副本会同时保留资料库中的版本。</p>';for(const id of ids){const r=await Store.get('records',id),error=queue.find(q=>q.recordId===id&&q.error);html+=`<div class="setting-section"><h3>${esc(r?.title||id)}</h3><p>${esc(error.error)}</p><button data-copy-conflict="${esc(id)}">将我的修改另存为副本</button><button data-retry-conflict="${esc(id)}">重试原操作</button></div>`;}panel('待处理的修改',html);}
async function copyConflict(id){try{const r=await Store.get('records',id);if(!r?.content)throw new Error('没有可另存的正文，请重试原操作或查看草稿。');const next={...r,id:uid(),title:r.title+'（我的副本）',version:1,deletedAt:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};await Store.enqueue({id:uid(),recordId:next.id,action:'create',record:next,createdAt:Date.now()},next);for(const op of await Store.all('queue'))if(op.recordId===id)await Store.remove('queue',op.id);try{await Store.put('records',await api('/api/records/'+id));}catch{}await sync();$('panelDialog').close();await refreshStats();await loadList();toast('你的修改已另存为副本。');}catch(e){toast(e.message);}}
async function settings(){await refreshStats();panel('参赛体验版 · 设置',"<section class=\"setting-section\"><h3>浏览器独立保存</h3><p>这份作品可在线体验。记录、三级类目和草稿保存在当前浏览器，其他访客看不到；清除浏览器数据会移除这些内容。</p><p>正式桌面版还支持自选资料目录和自动数据库备份。</p></section><section class=\"setting-section\"><h3>完整备份与恢复</h3><button class=\"primary\" data-action=\"backup\">下载当前浏览器的完整备份</button><button data-action=\"import-pick\">导入备份</button><input id=\"importFile\" type=\"file\" accept=\".json,application/json\" hidden><div id=\"importPreview\"></div></section><section class=\"setting-section\"><h3>草稿与外观</h3><button data-action=\"drafts\">查看未完成草稿</button><button data-action=\"theme\">切换明暗主题</button></section>");$('importFile').addEventListener('change',importPreview);}
function renderStorageSettings(){
 const s=state.stats;
 $('panelBody').insertAdjacentHTML('afterbegin',`<section class="setting-section"><h3>日常自动保存位置</h3><p>记录数据库与附件会持续写入此目录。更换目录时先复制并校验全部资料，切换后自动重启；旧目录原样保留。</p><p>当前：${esc(s.dataDir)}</p><label class="field">新资料文件夹（必须为空）<input id="dataDirectory" placeholder="输入新文件夹的完整路径"></label><button data-action="move-data-directory">迁移并切换日常保存位置</button><p id="storageMoveResult" class="muted"></p></section><section class="setting-section"><h3>自动快照与完整备份位置</h3><p>设置后，每 6 小时的数据库快照会写入这里；下方也可立即生成包含附件的完整备份。</p><p id="backupLocationCurrent">当前：${esc(s.backupDir||'项目内 backups 文件夹')}</p><label class="field">备份文件夹<input id="autoBackupDirectory" placeholder="输入备份文件夹的完整路径"></label><button data-action="set-backup-directory">设为默认备份位置</button></section>`);
 $('dataDirectory').value=s.dataDir;
 $('autoBackupDirectory').value=s.backupDir||'';
 $('backupDirectory').value=s.backupDir||'';
}
async function saveBackupDirectory(){
 try{const directory=$('autoBackupDirectory').value.trim();if(!directory)throw new Error('请输入备份文件夹路径');const result=await api('/api/storage/backup-location',{method:'POST',body:JSON.stringify({directory})});$('backupDirectory').value=result.backupDir;$('backupLocationCurrent').textContent='当前：'+result.backupDir;await refreshStats();toast('默认备份位置已更新，自动快照会保存到新目录。');}
 catch(error){toast(error.message||'备份位置设置失败');}
}
async function moveDataDirectory(){
 try{
  const directory=$('dataDirectory').value.trim();if(!directory)throw new Error('请输入新资料文件夹路径');
  if((await Store.all('queue')).length)throw new Error('还有修改尚未写入资料库，请先处理再切换位置。');
  $('storageMoveResult').textContent='正在复制并校验资料，请保持程序运行…';
  const result=await api('/api/storage/data-location',{method:'POST',body:JSON.stringify({directory})});
  if(!result.restarting){$('storageMoveResult').textContent='已经是当前资料位置。';return;}
  $('storageMoveResult').textContent='资料已复制，正在切换资料库…';
  let ready=false;
  for(let i=0;i<100;i++){
    await new Promise(resolve=>setTimeout(resolve,300));
    try{const response=await fetch('/api/health',{cache:'no-store',signal:AbortSignal.timeout(1000)});if(!response.ok)continue;const health=await response.json();if(health.dataDir.toLocaleLowerCase()===result.dataDir.toLocaleLowerCase()&&health.vaultId===result.vaultId){ready=true;break;}}catch{}
  }
  if(!ready)throw new Error('资料已复制，但自动重启未完成。旧目录仍保留；请用启动脚本重新打开资料库。');
  $('panelDialog').close();await refreshStats();await loadList();toast('日常保存位置已切换，旧资料仍保留在原目录。');
 }catch(error){$('storageMoveResult').textContent=error.message||'位置切换失败，旧目录未删除。';toast(error.message||'资料位置切换失败');}
}
async function backup(){
 const name='知识库备份-'+new Date().toISOString().slice(0,10)+'.json';
 let handle=null;
 try{
   if(typeof window.showSaveFilePicker==='function'){
     try{handle=await window.showSaveFilePicker({suggestedName:name,types:[{description:'知识库完整备份',accept:{'application/json':['.json']}}]});}
     catch(error){if(error.name==='AbortError')return;throw error;}
   }
   if((await Store.all('queue')).length)throw new Error('还有修改尚未写入资料库，请先同步或处理冲突。');
   toast('正在准备包含附件的备份…');
   const data=await api('/api/backup'),content=JSON.stringify(data);
   if(handle){const writable=await handle.createWritable();try{await writable.write(content);await writable.close();}catch(error){await writable.abort?.().catch(()=>{});throw error;}toast('完整备份已保存到所选位置。');}
   else{download(name,content);toast('备份已下载；可在浏览器下载设置中选择保存位置。');}
 }catch(error){toast(error.message||'备份未保存，请重试。');}
}
async function backupToDirectory(){
 try{
   const directory=$('backupDirectory').value.trim();
   if(!directory)throw new Error('请输入备份文件夹路径');
   if((await Store.all('queue')).length)throw new Error('还有修改尚未写入资料库，请先同步或处理冲突。');
   toast('正在保存完整备份…');
   const result=await api('/api/backup/save',{method:'POST',body:JSON.stringify({directory})});
   localStorage.setItem('kb-backup-dir',directory);
   $('backupPathResult').textContent='已保存到：'+result.path;
   toast('完整备份已保存到指定文件夹。');
 }catch(error){toast(error.message||'备份未保存，请检查路径和磁盘权限。');}
}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function importPreview(event){const file=event.target.files[0];if(!file)return;try{if(file.size>95*1024*1024)throw new Error('备份超过 95MB，请使用使用说明中的文件夹恢复方式。');pendingImport=JSON.parse(await file.text());const result=await api('/api/import/preview',{method:'POST',body:JSON.stringify({backup:pendingImport})});$('importPreview').innerHTML=`<div class="banner" style="display:block"><p>共 ${result.total} 条，新增 ${result.added} 条，重复 ${result.conflicts} 条，附件 ${result.attachments} 个，自建类目 ${result.categories} 个。${result.verified?'校验通过。':'旧格式，无校验码。'}</p><label class="field">重复记录处理<select id="importMode"><option value="skip">保留现有记录，跳过重复项</option><option value="overwrite">用备份覆盖重复项（先自动备份）</option></select></label><button class="primary" data-action="import-confirm">确认导入</button></div>`;}catch(e){pendingImport=null;toast(e.message);}}
async function importConfirm(){try{if((await Store.all('queue')).length)throw new Error('请先处理尚未同步的修改，再导入备份。');if(!pendingImport)return;const result=await api('/api/import',{method:'POST',body:JSON.stringify({backup:pendingImport,mode:$('importMode').value})});pendingImport=null;$('panelDialog').close();toast(`导入完成：新增 ${result.added}，更新 ${result.updated}，跳过 ${result.skipped}`);await refreshStats();await loadList();}catch(e){toast(e.message);}}
async function legacy(){let records;try{records=JSON.parse(localStorage.getItem('knowledge_base_records')||'[]');}catch{records=[];}if(!Array.isArray(records)||!records.length){toast('当前浏览器地址下没有旧版缓存。');return;}panel('恢复旧版浏览器记录',`<p>发现 ${records.length} 条旧版缓存。将以新副本导入，保留现有记录。</p><button class="primary" data-action="legacy-confirm">恢复为副本</button>`);}
async function legacyConfirm(){try{const records=JSON.parse(localStorage.getItem('knowledge_base_records')||'[]');for(const old of records){const r={...old,id:uid(),title:(old.title||'旧版记录')+'（恢复）',content:sanitize(old.content),version:1,deletedAt:null};await Store.enqueue({id:uid(),recordId:r.id,action:'create',record:r,createdAt:Date.now()},r);}await sync();$('panelDialog').close();toast('已恢复旧版缓存，原缓存仍保留。');await refreshStats();await loadList();}catch(e){toast(e.message);}}
function showLogin(){if($('loginPassword')&&$('panelDialog').open)return;panel('连接共享资料库','<p>请输入在主机上设置的共享口令。</p><label class="field">共享口令<input id="loginPassword" type="password" autocomplete="current-password"></label><button class="primary" data-action="login">连接</button>');}
async function login(){try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('loginPassword').value})});$('panelDialog').close();if(!state.ready){await boot();return;}await sync();await refreshStats();await loadList();}catch(e){toast(e.message);}}
function rememberRange(){const sel=getSelection();if(sel.rangeCount&&$('content').contains(sel.anchorNode))lastRange=sel.getRangeAt(0).cloneRange();}
function restoreRange(){$('content').focus();if(lastRange&&$('content').contains(lastRange.commonAncestorContainer)){const sel=getSelection();sel.removeAllRanges();sel.addRange(lastRange);}}
function insertHTML(html){restoreRange();document.execCommand('insertHTML',false,sanitize(html));rememberRange();scheduleDraft();}
async function attach(files){state.uploading=(state.uploading||0)+1;for(const file of files){if(file.size>50*1024*1024){toast('单个附件不能超过 50MB。');continue;}if(!/^image\/(png|jpeg|gif|webp)$|^video\/(mp4|webm)$/.test(file.type)){toast('支持 PNG、JPEG、GIF、WebP、MP4 和 WebM。');continue;}try{let url;if(state.online){const result=await api('/api/attachments',{method:'POST',body:file,binary:true,headers:{'Content-Type':'application/octet-stream'}});url=result.url;}else{url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}insertHTML(file.type.startsWith('image/')?`<img src="${esc(url)}" alt="${esc(file.name)}" style="width:100%"><p><br></p>`:`<video controls src="${esc(url)}" style="width:100%"></video><p><br></p>`);await writeDraft();toast(state.online?'附件已添加':'附件已保存在草稿，联网保存时上传');}catch(e){toast(e.message||'附件添加失败');}}state.uploading--; $('attachment').value='';}
function selectMedia(el){if(state.selectedMedia)state.selectedMedia.classList.remove('selected-media');state.selectedMedia=el;$('mediaControls').hidden=!el;$('resizeHandle').hidden=!el;if(el){el.classList.add('selected-media');const percent=Math.round(el.getBoundingClientRect().width/$('content').clientWidth*100);$('mediaWidth').value=percent;$('mediaPercent').textContent=percent+'%';positionHandle();}}
function positionHandle(){const el=state.selectedMedia;if(!el)return;const rect=el.getBoundingClientRect();$('resizeHandle').style.left=(rect.right-8)+'px';$('resizeHandle').style.top=(rect.bottom-8)+'px';}
function setMediaWidth(value){if(!state.selectedMedia)return;value=Math.min(100,Math.max(10,value));state.selectedMedia.style.width=value+'%';state.selectedMedia.style.height='auto';$('mediaPercent').textContent=Math.round(value)+'%';$('mediaWidth').value=value;positionHandle();scheduleDraft();}
async function action(name){switch(name){case'menu':$('sidebar').classList.toggle('open');$('shade').hidden=!$('sidebar').classList.contains('open');break;case'new':await openEditor();break;case'theme':document.body.classList.toggle('dark');localStorage.setItem('knowledge_base_theme',document.body.classList.contains('dark')?'dark':'light');break;case'clear-filter':resetFilters();state.page=1;await loadList();await refreshStats();break;case'reset-filters':resetFilters();state.page=1;await loadList();await refreshStats();break;case'prev':state.page--;await loadList();break;case'next':state.page++;await loadList();break;case'sync':if(!state.ready){await boot();break;}await sync();await refreshStats();await loadList();if(!state.pending)toast(state.online?'资料库已连接，修改已同步':'无法连接，修改仍保存在此浏览器');break;case'add-category':showAddCategory();break;case'save-category':await saveCategory();break;case'settings':await settings();break;case'drafts':await showDrafts();break;case'conflicts':await conflicts();break;case'close-panel':$('panelDialog').close();break;case'close-detail':hidePane($('detailDialog'));state.detail=null;renderList();break;case'edit-detail':await openEditor(state.detail);break;case'history':await showHistory();break;case'focus-editor':document.body.classList.toggle('focus-mode');break;case'favorite':await favorite(state.detail.id);break;case'delete-detail':await trash(state.detail.id);break;case'pdf':window.print();break;case'backup':await backup();break;case'backup-directory':await backupToDirectory();break;case'set-backup-directory':await saveBackupDirectory();break;case'move-data-directory':await moveDataDirectory();break;case'import-pick':$('importFile').click();break;case'import-confirm':await importConfirm();break;case'legacy':await legacy();break;case'legacy-confirm':await legacyConfirm();break;case'local-export':{const queued=await Store.all('queue');const ids=[...new Set(queued.map(q=>q.recordId))];const records=[];for(const id of ids){const r=await Store.get('records',id);if(r)records.push(r);}download('待同步内容-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({format:'knowledge-base',version:2,records,drafts:await Store.all('drafts')}));toast('本地内容已导出；已上传附件仍需保留原附件目录。');break;}case'login':await login();break;case'attach':rememberRange();$('attachment').click();break;case'link':{rememberRange();const href=prompt('输入完整链接（https://…）');if(href){if(!/^https?:\/\//i.test(href)){toast('请输入 http 或 https 链接');break;}restoreRange();if(getSelection().isCollapsed)insertHTML(`<a href="${esc(href)}">${esc(href)}</a>`);else{document.execCommand('createLink',false,href);scheduleDraft();}}break;}case'remove-media':state.selectedMedia?.remove();selectMedia(null);scheduleDraft();break;case'demo':await openEditor(null,{id:'new-'+uid(),title:'欢迎来到我的知识库',content:'<h2>从一个想法开始</h2><p>记录阅读摘录、学习笔记和灵感。选中文字设置格式，或添加图片和视频。</p><ul><li>保存后记录写入本机资料库。</li><li>关闭编辑器，草稿仍可继续编辑。</li><li>误删记录可从回收站恢复。</li></ul>',tags:'使用指南'});break;}}
$('tags').addEventListener('contextmenu',showCategoryContextMenu);
$('categoryContextCreate').addEventListener('click',()=>{const id=$('categoryContextMenu').dataset.parentId;if(!id)return;hideCategoryContextMenu();showAddCategory(id);});
document.addEventListener('pointerdown',event=>{if(!$('categoryContextMenu').contains(event.target))hideCategoryContextMenu();},true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('categoryContextMenu').hidden){event.preventDefault();event.stopImmediatePropagation();hideCategoryContextMenu();}else if((event.key==='ContextMenu'||event.shiftKey&&event.key==='F10')&&event.target.closest?.('.category-row')){const rect=event.target.getBoundingClientRect();showCategoryContextMenu({target:event.target,clientX:rect.left+20,clientY:rect.bottom,preventDefault:()=>event.preventDefault()});}},true);
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;try{if(b.dataset.action)await action(b.dataset.action);else if(b.dataset.view){state.view=b.dataset.view;state.tag='';state.categoryId='';state.page=1;if(state.view==='recent'){state.sort='updated-desc';$('sort').value=state.sort;}await loadList();$('sidebar').classList.remove('open');$('shade').hidden=true;await refreshStats();}else if(b.dataset.tag){state.tag=b.dataset.tag;state.categoryId='';state.view='all';state.page=1;await loadList();await refreshStats();$('sidebar').classList.remove('open');$('shade').hidden=true;}else if(b.dataset.category){state.categoryId=b.dataset.category;state.tag='';state.view='all';state.page=1;await loadList();await refreshStats();}else if(b.dataset.expandCategory){const id=b.dataset.expandCategory;state.collapsedCategories.has(id)?state.collapsedCategories.delete(id):state.collapsedCategories.add(id);$('tags').innerHTML=renderCategoryTree(state.stats);}else if(b.dataset.addChild){showAddCategory(b.dataset.addChild);}else if(b.dataset.filterTag){const tag=b.dataset.filterTag;state.filterTags=state.filterTags.includes(tag)?state.filterTags.filter(t=>t!==tag):[...state.filterTags,tag];state.page=1;renderSearchFilters();await loadList();}else if(b.dataset.layout){state.layout=b.dataset.layout;localStorage.setItem('kb-layout',state.layout);renderList();}else if(b.dataset.open)await openDetail(b.dataset.open);else if(b.dataset.historyVersion)await showHistoryVersion(b.dataset.historyVersion);else if(b.dataset.restoreVersion)await restoreVersion(b.dataset.restoreVersion);else if(b.dataset.favorite)await favorite(b.dataset.favorite);else if(b.dataset.restore)await trash(b.dataset.restore,true);else if(b.dataset.draft){const d=await Store.get('drafts',b.dataset.draft);await openEditor(d.base,d);}else if(b.dataset.copyConflict)await copyConflict(b.dataset.copyConflict);else if(b.dataset.retryConflict){for(const op of await Store.all('queue'))if(op.recordId===b.dataset.retryConflict){delete op.error;await Store.put('queue',op);}await sync();await conflicts();}else if(b.dataset.quickTag){const tags=selectedTags(),tag=b.dataset.quickTag;$('editTags').value=(tags.includes(tag)?tags.filter(t=>t!==tag):[...tags,tag]).join('，');scheduleDraft();}else if(b.dataset.command){restoreRange();document.execCommand(b.dataset.command,false,b.dataset.value||null);rememberRange();scheduleDraft();}}catch(e){toast(e.message);}});
$('search').addEventListener('input',()=>{clearTimeout(state.searchTimer);state.searchTimer=setTimeout(()=>{state.q=$('search').value.trim();state.page=1;loadList();},250);});$('sort').addEventListener('change',()=>{state.sort=$('sort').value;state.page=1;loadList();});$('shade').addEventListener('click',()=>{$('sidebar').classList.remove('open');$('shade').hidden=true;});
for(const [id,key] of [['filterFrom','filterFrom'],['filterTo','filterTo'],['filterMedia','filterMedia']])$(id).addEventListener('change',()=>{state[key]=$(id).value;state.page=1;renderSearchFilters();loadList();});$('filterUntagged').addEventListener('change',()=>{state.filterUntagged=$('filterUntagged').checked;state.page=1;renderSearchFilters();loadList();});
$('closeEditor').addEventListener('click',event=>{event.preventDefault();closeEditor();});$('editorDialog').addEventListener('cancel',event=>{event.preventDefault();closeEditor();});$('saveEditor').addEventListener('click',()=>saveEditor({close:true}));
for(const id of ['editTitle','editTags','editCategory','content'])$(id).addEventListener('input',scheduleDraft);$('attachment').addEventListener('change',e=>attach(e.target.files));$('content').addEventListener('keyup',rememberRange);$('content').addEventListener('mouseup',rememberRange);document.querySelector('.toolbar').addEventListener('mousedown',e=>{if(e.target.closest('button')){rememberRange();e.preventDefault();}});
$('content').addEventListener('paste',event=>{event.preventDefault();rememberRange();const files=[...event.clipboardData.files];if(files.length){attach(files);return;}const html=event.clipboardData.getData('text/html'),text=event.clipboardData.getData('text/plain');insertHTML(html||esc(text).replace(/\n/g,'<br>'));});$('content').addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('Files'))e.preventDefault();});$('content').addEventListener('drop',e=>{e.preventDefault();if(e.dataTransfer.files.length)attach(e.dataTransfer.files);});$('content').addEventListener('click',e=>selectMedia(e.target.closest('img,video')));$('mediaWidth').addEventListener('input',e=>setMediaWidth(Number(e.target.value)));
$('resizeHandle').addEventListener('pointerdown',e=>{e.preventDefault();const handle=$('resizeHandle');handle.setPointerCapture(e.pointerId);const left=state.selectedMedia.getBoundingClientRect().left;const move=event=>setMediaWidth((event.clientX-left)/$('content').clientWidth*100);const end=()=>{handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',end);};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end);});$('editorDialog').addEventListener('scroll',positionHandle);window.addEventListener('resize',positionHandle);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'&&$('editorDialog').open){e.preventDefault();saveEditor({auto:false,close:false});}if(e.key==='Escape'&&sidePane()&&$('editorDialog').open&&!$('editorDialog').classList.contains('editor-overlay')&&!$('panelDialog').open){e.preventDefault();closeEditor();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&!$('editorDialog').open){e.preventDefault();$('search').focus();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'&&!$('editorDialog').open){e.preventDefault();openEditor();}});window.addEventListener('beforeunload',e=>{if($('editorDialog').open&&state.draftId&&state.editRevision>state.lastSavedRevision){writeDraft().catch(()=>{});e.preventDefault();e.returnValue='';}});window.addEventListener('online',async()=>{if(!state.ready)return;await sync();await refreshStats();await loadList();});window.addEventListener('offline',()=>{state.online=false;connection();});
async function boot(){document.body.classList.toggle('dark',localStorage.getItem('knowledge_base_theme')==='dark');let vaultId=localStorage.getItem('kb-vault-id');try{const health=await api('/api/health');if(health.version!=='2.3.3')throw new Error('当前地址是旧版服务，请使用新版启动入口。');vaultId=health.vaultId;localStorage.setItem('kb-vault-id',vaultId);}catch(error){if(error.status===401)return;if(!vaultId){$('records').innerHTML='<div class="empty"><h2>暂时无法连接资料库</h2><p>请运行项目里的启动脚本，再刷新此页。</p><button data-action="sync">重试连接</button></div>';return;}}try{await Store.open(vaultId);state.ready=true;await sync();await refreshStats();await loadList();await draftBanner();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});}catch(e){$('records').innerHTML=`<div class="empty"><h2>本地存储不可用</h2><p>${esc(e.message)}。请检查浏览器存储权限和磁盘空间。</p></div>`;}}
editorDialog.append(resizeHandle);
setInterval(async()=>{if(!state.ready||document.hidden||state.saving)return;try{await api('/api/health');await sync();}catch{}},30000);boot();
